Repository DASOM-GitHub/dasom-web-frontend, pull requests merged in 2025-03, with the labels that each got.

#96 [feat] 어드민 공지사항 API 연동 완료
  src/App.tsx
  src/components/UI/NewsFileUpload.tsx
  src/components/UI/NewsTextEditor.tsx
  src/pages/Login.tsx
  src/pages/admin/AdminMain.tsx
  src/pages/admin/ManApplicants.tsx
  src/pages/admin/ManNewsDetail.tsx
  src/pages/admin/ManNewsEdit.tsx
  src/pages/admin/ManNewsList.tsx
  src/pages/admin/ManNewsPost.tsx
  src/pages/admin/ManRecruitDate.tsx
Labels: FEAT

#99 [feat] news 페이지,상세페이지 api 연동 & 스와이퍼 아이콘 커스텀 스타일 변경
  src/assets/styles/index.css
  src/components/UI/NewsContent.tsx
  src/components/UI/NewsNotice.tsx
  src/pages/News.tsx
  src/pages/NewsInfo.tsx
Labels: FEAT

#98 [docs] 리드미, 라이센스 추가
  LICENSE
  README.md
Labels: DOCS

#101 feat: 도메인주소 변경 & 이름 필드 제약조건 추가
  src/components/UI/RecruitUI.tsx
  src/components/UI/Recruit_InputField.tsx
  src/pages/Recruit.tsx
Labels: FEAT

#103 [feat] 면접 예약 페이지 API 연동 - 2
  src/components/UI/MeetingDate.tsx
  src/components/UI/MeetingDateSelector.tsx
  src/components/UI/MeetingTime.tsx
  src/components/UI/MeetingTimeSelector.tsx
  src/pages/RecruitCheck.tsx
  src/pages/RecruitMeeting.tsx
  src/pages/RecruitResult.tsx
  src/pages/RecruitSubmitMeeting.tsx
  src/pages/admin/ManRecruitDate.tsx
Labels: FEAT

#106 [fix] 합격여부 컴포넌트 레이아웃 수정
  src/components/UI/RecruitUI.tsx
Labels: BUG

#107 [feat] 어드민 면접자 조회 페이지 구현
  src/App.tsx
  src/components/UI/AdminPagination.tsx
  src/pages/Recruit.tsx
  src/pages/admin/ManApplicants.tsx
  src/pages/admin/ManInterviewee.tsx
Labels: FEAT

#112 [fix] 지원폼 덮어쓰기 추가 & activity 필수입력 제거 & 배너 레이아웃 수정
  src/components/UI/Recruit_InfoBanner.tsx
  src/pages/Recruit.tsx
Labels: BUG

#114 [feat] 면접 예약 페이지 시간 선택 비활성화 추가
  src/components/UI/MeetingTimeSelector.tsx
  src/components/UI/Recruit_Button.tsx
  src/pages/RecruitMeeting.tsx
Labels: FEAT

#116 [fix] 지원자 폼 페이지 자동확대 방지
  public/index.html
Labels: BUG

#120 [fix] 면접예약 페이지 배너 수정
  src/pages/RecruitMeeting.tsx
Labels: BUG

#128 feat: RecriotCheck 페이지 제약조건 추가
  src/pages/RecruitResult.tsx
Labels: FEAT

#131 [refactor] News, NewsInfo 통신문법 수정 및 기타페이지 공백 제거
  src/components/UI/AdminPagination.tsx
  src/components/UI/FAQ_Section.tsx
  src/components/UI/Header.tsx
  src/components/UI/MeetingDate.tsx
  src/components/UI/MeetingDateSelector.tsx
  src/components/UI/MeetingTime.tsx
  src/components/UI/MeetingTimeSelector.tsx
  src/components/UI/NewsContent.tsx
  src/components/UI/NewsNotice.tsx
  src/components/UI/NewsTextEditor.tsx
  src/components/UI/RecruitUI.tsx
  src/components/UI/Recruit_Button.tsx
  src/components/UI/Recruit_InputField.tsx
  src/pages/News.tsx
  src/pages/NewsInfo.tsx
  src/pages/Recruit.tsx
  src/pages/RecruitCheck.tsx
  src/pages/RecruitCheckFinal.tsx
  src/pages/RecruitMeeting.tsx
  src/pages/RecruitResult.tsx
  src/pages/RecruitSubmit.tsx
  src/pages/RecruitSubmitMeeting.tsx
  src/pages/UserMain.tsx
Labels: REFACTOR

#133 [fix] 면접 장소 안내 없음 수정
  src/components/UI/RecruitUI.tsx
  src/pages/RecruitSubmitMeeting.tsx
Labels: BUG

#142 [fix] 어드민 지원자 목록 페이지네이션 로직 수정
  src/components/UI/AdminPagination.tsx
  src/pages/admin/ManApplicants.tsx
  src/pages/admin/ManInterviewee.tsx
  src/pages/admin/ManNewsList.tsx
Labels: BUG

#148 [refactor] 디버깅용 로그 주석처리
  src/pages/Login.tsx
  src/pages/RecruitMeeting.tsx
  src/pages/RecruitResult.tsx
  src/pages/admin/ManApplicants.tsx
  src/pages/admin/ManNewsDetail.tsx
  src/pages/admin/ManNewsList.tsx
  src/pages/admin/ManNewsPost.tsx
  src/pages/admin/ManRecruitDate.tsx
Labels: REFACTOR

#151 [refactor] 코드 오타 수정
  src/components/UI/MailButtons.tsx
Labels: REFACTOR

#153 [feat] 헤더 로직 수정
  src/components/UI/Header.tsx
Labels: FEAT
