Repository DASOM-GitHub/dasom-web-frontend, pull requests merged in 2025-02, with the labels that each got.

#2 [feat] 헤더구현
  src/App.tsx
  src/assets/images/headerMenu.svg
  src/components/UI/Header.tsx
  src/components/layout/mobileLayout.tsx
Labels: FEAT

#4 [fix] 헤더 테스트 및 tailwind 설정 수정
  postcss.config.js
  src/App.tsx
  src/assets/styles/index.css
  src/components/UI/Header.tsx
  src/pages/Main.tsx
  tailwind.config.js
Labels: BUG

#9 [feat] 헤더 클릭이벤트완료 + 폰트파일 추가 및 css 설정수정
  public/fonts/Pretendard-Black.woff
  public/fonts/Pretendard-Bold.woff
  public/fonts/Pretendard-ExtraBold.woff
  public/fonts/Pretendard-ExtraLight.woff
  public/fonts/Pretendard-Light.woff
  public/fonts/Pretendard-Medium.woff
  public/fonts/Pretendard-Regular.woff
  public/fonts/Pretendard-SemiBold.woff
  public/fonts/Pretendard-Thin.woff
  src/assets/images/headerMenuUndo.svg
  src/assets/styles/index.css
  src/components/UI/Header.tsx
  tailwind.config.js
Labels: INFRA, FEAT

#10 [fix/#2-4] <moblieLayout> 제거 <div> 추가 & 헤더 클릭 이벤트 css 설정수정
  src/components/UI/Header.tsx
Labels: BUG

#13 [feat] react-router-dom 라이브러리 추가
  .gitignore
  package.json
  src/App.tsx
  yarn.lock
Labels: INFRA, FEAT

#16 [fix] 코어멤버 페이지 css 수정
  src/pages/CoreMembers.tsx
Labels: BUG

#18 [fix] Header 및 MobileLayout 반응형으로 수정
  src/components/UI/Header.tsx
  src/components/layout/MobileLayout.tsx
  src/hooks/useWindowSize.tsx
Labels: BUG, REFACTOR

#23 [infra] Cover Library 추가 및 Header, Main 레이아웃 수정
  components.json
  package-lock.json
  package.json
  src/App.test.tsx
  src/assets/styles/index.css
  src/components/UI/Header.tsx
  src/components/UI/cover.tsx
  src/components/UI/sparkles.tsx
  src/pages/Main.tsx
  src/utils/utils.ts
  tailwind.config.js
  tsconfig.json
  yarn.lock
Labels: INFRA, FEAT

#20 [feat] Recruit 페이지 & UI 컴포넌트, Button 컴포넌트, InputField 컴포넌트 추가
  src/components/UI/RecruitUI.tsx
  src/components/UI/Recruit_Button.tsx
  src/components/UI/Recruit_InputField.tsx
  src/pages/Recruit.tsx
Labels: FEAT

#26 [feat] 면접 예약 페이지 구현
  package.json
  src/App.tsx
  src/components/UI/MeetingDate.tsx
  src/components/UI/MeetingTime.tsx
  src/components/layout/MeetingDateSelector.tsx
  src/components/layout/MeetingTimeSelector.tsx
  src/pages/RecruitMeeting.tsx
  src/pages/RecruitSubmitMeeting.tsx
Labels: FEAT

#28 [fix] 헤더 팝업 에러수정
  src/components/UI/Header.tsx
Labels: BUG

#30 [fix] MobileLayout 오류 수정
  src/components/layout/MobileLayout.tsx
Labels: BUG

#31 [feat] 메인페이지 구현
  src/assets/images/activityBar.svg
  src/assets/images/pythonCross.svg
  src/assets/images/pythonDown.svg
  src/assets/images/pythonExtra.svg
  src/assets/images/pythonFocus.svg
  src/assets/images/pythonMain.svg
  src/assets/images/pythonMeetballs.svg
  src/assets/images/pythonMerge.svg
  src/assets/images/pythonPlus.svg
  src/assets/images/pythonRecruit.svg
  src/assets/images/pythonRunAll.svg
  src/assets/images/pythonSplit.svg
  src/assets/images/pythonStart.svg
  src/components/UI/ActivityStatus.tsx
  src/pages/Main.tsx
Labels: FEAT

#35 [design] Main 애니메이션 완료
  src/assets/images/github.svg
  src/assets/images/instagram.svg
  src/components/UI/ActivityStatus.tsx
  src/pages/Main.tsx
Labels: DESIGN

#33 [feat] News 페이지 구현
  src/App.tsx
  src/assets/images/newsBannerExam.svg
  src/components/UI/NewsContent.tsx
  src/components/UI/NewsNotice.tsx
  src/pages/News.tsx
  src/pages/NewsInfo.tsx
Labels: FEAT

#38 [feat] 페이지 route 추가, Header 페이지 이동 추가
  src/App.tsx
  src/components/UI/Header.tsx
  src/pages/CoreMembers.tsx
  src/pages/Main.tsx
  src/pages/News.tsx
  src/pages/NewsInfo.tsx
  src/pages/Recruit.tsx
  src/pages/RecruitMeeting.tsx
  src/pages/RecruitSubmitMeeting.tsx
Labels: REFACTOR, FEAT

#39 [feat] RecruitSubmit, RecruitResult, RecruitCheck 페이지 구현 및 컴포넌트 추가 수정
  src/components/UI/RecruitUI.tsx
  src/components/UI/Recruit_Button.tsx
  src/components/UI/Recruit_InfoBanner.tsx
  src/components/UI/Recruit_InputField.tsx
  src/pages/Recruit.tsx
  src/pages/RecruitCheck.tsx
  src/pages/RecruitResult.tsx
  src/pages/RecruitSubmit.tsx
Labels: FEAT, DESIGN

#41 [fix] 로그인 구현 완료
  src/App.tsx
  src/pages/Login.tsx
  src/pages/UserMain.tsx
Labels: FEAT

#40 [feat] 관리자 메인 페이지, 지원자 관리 페이지 구현
  package-lock.json
  package.json
  src/App.tsx
  src/pages/admin/AdminMain.tsx
  src/pages/admin/ManApplicants.tsx
  yarn.lock
Labels: FEAT

#50 [infra] Create dev.yml
  .github/workflows/dev.yml
Labels: INFRA

#46 [fix] App.tsx 수정
  src/App.tsx
Labels: BUG

#49 [feat] FAQ 페이지 & FAQ 컴포넌트 구현
  src/components/UI/FAQ_Section.tsx
  src/pages/FAQ.tsx
Labels: FEAT

#54 hotfix: vercel 배포오류수정
  package-lock.json
  package.json
  yarn.lock
Labels: BUG, HOTFIX

#57 [feat] Recruit 페이지 api 기능 추가
  src/components/UI/Recruit_InputField.tsx
  src/pages/Recruit.tsx
Labels: FEAT

#60 [hotfix] vercel용 환경설정 파일 추가
  vercel.json
Labels: BUG, HOTFIX

#58 [feat] 어드민 일정 관리 페이지 구현
  package-lock.json
  package.json
  src/App.tsx
  src/pages/admin/ManApplicants.tsx
  src/pages/admin/ManRecruitDate.tsx
Labels: FEAT

#65 [fix] RecruitMeeting 페이지 버튼 컴포넌트 추가 & Result 컴포넌트 코드 수정
  src/components/UI/Recruit_Button.tsx
  src/components/UI/Recruit_InfoBanner.tsx
  src/pages/Recruit.tsx
  src/pages/RecruitMeeting.tsx
  src/pages/RecruitResult.tsx
  src/pages/RecruitSubmit.tsx
Labels: BUG

#67 [fix] 페이지 레이아웃 수정 + Route 추가
  src/App.tsx
  src/components/UI/FAQ_Section.tsx
  src/components/UI/Header.tsx
  src/components/UI/RecruitUI.tsx
  src/components/UI/Recruit_InfoBanner.tsx
  src/components/UI/Recruit_InputField.tsx
  src/pages/FAQ.tsx
  src/pages/Main.tsx
  src/pages/Recruit.tsx
  src/pages/RecruitMeeting.tsx
  src/pages/RecruitResult.tsx
  src/pages/RecruitSubmitMeeting.tsx
Labels: REFACTOR, FEAT, DESIGN

#68 [feat] 어드민 일정 관리 페이지 API 연동
  src/pages/Login.tsx
  src/pages/admin/ManRecruitDate.tsx
Labels: FEAT

#69 [feat] 면접 예약 페이지 API 연동
  src/components/UI/MeetingDateSelector.tsx
  src/components/UI/MeetingTimeSelector.tsx
  src/components/layout/MeetingDateSelector.tsx
  src/components/layout/MeetingTimeSelector.tsx
  src/pages/RecruitMeeting.tsx
Labels: FEAT

#71 [feat] RecruitUI 컴포넌트의 모집일정 API 연동 & RecruitUI_SUB 컴포넌트 텍스트 최신화
  src/components/UI/RecruitUI.tsx
Labels: FEAT

#73 [refactor] 메인페이지 코드 간결화
  src/components/UI/Header.tsx
  src/components/UI/PythonEditor.tsx
  src/pages/Main.tsx
Labels: REFACTOR

#77 [design] 메인페이지 디자인 수정
  src/components/UI/ParticlesBackground.tsx
  src/pages/Main.tsx
Labels: DESIGN

#80 [feat] 합격 조회 페이지 API 연동
  src/App.tsx
  src/components/UI/RecruitUI.tsx
  src/components/UI/Recruit_InputField.tsx
  src/pages/RecruitCheck.tsx
  src/pages/RecruitCheckFinal.tsx
  src/pages/RecruitResult.tsx
Labels: FEAT

#84 [fix] 어드민 페이지 접근 보안 추가
  src/App.tsx
  src/components/layout/ProtectRoute.tsx
Labels: REFACTOR

#78 [feat] 어드민 소식 목록 및 작성 페이지 UI 완료, API 연결 중
  package-lock.json
  src/App.tsx
  src/components/UI/AdminPagination.tsx
  src/pages/CoreMembers.tsx
  src/pages/admin/AdminMain.tsx
  src/pages/admin/ManApplicants.tsx
  src/pages/admin/ManNewsDetail.tsx
  src/pages/admin/ManNewsList.tsx
  src/pages/admin/ManNewsPost.tsx
  yarn.lock
Labels: BUG, FEAT

#82 [design] 페이지 애니메이션 추가
  src/components/UI/FAQ_Section.tsx
  src/pages/CoreMembers.tsx
  src/pages/FAQ.tsx
Labels: DESIGN

#86 [feat] swiper 라이브러리 설치
  package.json
  yarn.lock
Labels: FEAT

#92 [design] 파비콘 수정 및 title 수정
  public/icon3/android-icon-144x144.png
  public/icon3/android-icon-192x192.png
  public/icon3/android-icon-36x36.png
  public/icon3/android-icon-48x48.png
  public/icon3/android-icon-72x72.png
  public/icon3/android-icon-96x96.png
  public/icon3/apple-icon-114x114.png
  public/icon3/apple-icon-120x120.png
  public/icon3/apple-icon-144x144.png
  public/icon3/apple-icon-152x152.png
  public/icon3/apple-icon-180x180.png
  public/icon3/apple-icon-57x57.png
  public/icon3/apple-icon-60x60.png
  public/icon3/apple-icon-72x72.png
  public/icon3/apple-icon-76x76.png
  public/icon3/apple-icon-precomposed.png
  public/icon3/apple-icon.png
  public/icon3/browserconfig.xml
  public/icon3/favicon-16x16.png
  public/icon3/favicon-32x32.png
  public/icon3/favicon-96x96.png
  public/icon3/favicon.ico
  public/icon3/manifest.json
  public/icon3/ms-icon-144x144.png
  public/icon3/ms-icon-150x150.png
  public/icon3/ms-icon-310x310.png
  public/icon3/ms-icon-70x70.png
  public/index.html
  public/manifest.json
  src/assets/images/dasomLogo.png
  src/assets/images/dasomLogo2.png
  src/assets/images/dasomLogo3.png
Labels: DESIGN

#94 [design] 스크롤바 hidden 설정
  src/App.tsx
  src/assets/styles/index.css
  src/components/layout/MobileLayout.tsx
  src/index.tsx
  tailwind.config.js
Labels: DESIGN

#95 [fix] RecruitResult 호출 수정 & onKeyDown 추가, InputField 중복 수정
  src/components/UI/Recruit_InputField.tsx
  src/pages/RecruitResult.tsx
Labels: BUG

#88 [fix] recruit 폼 레이아웃 및 라벨 글자 색 수정
  src/components/UI/RecruitUI.tsx
  src/components/UI/Recruit_InputField.tsx
  src/pages/Recruit.tsx
Labels: BUG
