Repository DASOM-GitHub/dasom-web-frontend, pull requests merged in 2025-08, with the labels that each got.

#164 refactor/dasomfe-8-prettierrc-추가
  .prettierrc
  src/App.tsx
  src/assets/styles/index.css
  src/components/UI/ActivityStatus.tsx
  src/components/UI/AdminPagination.tsx
  src/components/UI/FAQ_Section.tsx
  src/components/UI/Header.tsx
  src/components/UI/MailButtons.tsx
  src/components/UI/MeetingDate.tsx
  src/components/UI/MeetingDateSelector.tsx
  src/components/UI/MeetingTime.tsx
  src/components/UI/MeetingTimeSelector.tsx
  src/components/UI/NewsContent.tsx
  src/components/UI/NewsFileUpload.tsx
  src/components/UI/NewsNotice.tsx
  src/components/UI/NewsTextEditor.tsx
  src/components/UI/ParticlesBackground.tsx
  src/components/UI/PythonEditor.tsx
  src/components/UI/RecruitUI.tsx
  src/components/UI/Recruit_Button.tsx
  src/components/UI/Recruit_InfoBanner.tsx
  src/components/UI/Recruit_InputField.tsx
  src/components/UI/cover.tsx
  src/components/UI/sparkles.tsx
  src/components/layout/MobileLayout.tsx
  src/components/layout/ProtectRoute.tsx
  src/hooks/useWindowSize.tsx
  src/index.tsx
  src/pages/CoreMembers.tsx
  src/pages/FAQ.tsx
  src/pages/Login.tsx
  src/pages/Main.tsx
  src/pages/News.tsx
  src/pages/NewsInfo.tsx
  src/pages/Recruit.tsx
  src/pages/RecruitCheck.tsx
  src/pages/RecruitCheckFinal.tsx
  src/pages/RecruitMeeting.tsx
  src/pages/RecruitResult.tsx
  src/pages/RecruitSubmit.tsx
  src/pages/RecruitSubmitMeeting.tsx
  src/pages/SomkathonRecruit.tsx
  src/pages/SomkathonSubmit.tsx
  src/pages/UserMain.tsx
  src/pages/admin/AdminMain.tsx
  src/pages/admin/ManApplicants.tsx
  src/pages/admin/ManInterviewee.tsx
  src/pages/admin/ManNewsDetail.tsx
  src/pages/admin/ManNewsEdit.tsx
  src/pages/admin/ManNewsList.tsx
  src/pages/admin/ManNewsPost.tsx
  src/pages/admin/ManRecruitDate.tsx
  src/pages/admin/SomkatonApplicants.tsx
  src/setupTests.ts
  src/utils/utils.ts
Labels: REFACTOR

#169 hotfix/dasomfe 10 자동연결 버그
  .github/workflows/jira-integration.yml
Labels: BUG

#171 hotfix/dasomfe 10 파일수정
  .github/ISSUE_TEMPLATE/🍀다솜-이슈-템플릿.md
  .github/ISSUE_TEMPLATE/🍀다솜-이슈-템플릿.yml
  .github/workflows/close-jira-issue.yml
  .github/workflows/create-jira-issue.yml
  .github/workflows/dev.yml
  .github/workflows/jira-integration.yml
Labels: HOTFIX

#178 hotfix/dasomfe 10 자동연결 버그
  .github/workflows/create-jira-issue.yml
Labels: BUG

#181 [Refactor] API 호출 로직 분리
  package-lock.json
  package.json
  src/components/UI/ActivityStatus.tsx
  src/components/UI/Header.tsx
  src/components/UI/MailButtons.tsx
  src/components/UI/RecruitUI.tsx
  src/pages/Login.tsx
  src/pages/News.tsx
  src/pages/NewsInfo.tsx
  src/pages/Recruit.tsx
  src/pages/RecruitMeeting.tsx
  src/pages/RecruitResult.tsx
  src/pages/SomkathonRecruit.tsx
  src/pages/admin/AdminMain.tsx
  src/pages/admin/ManApplicants.tsx
  src/pages/admin/ManInterviewee.tsx
  src/pages/admin/ManNewsDetail.tsx
  src/pages/admin/ManNewsEdit.tsx
  src/pages/admin/ManNewsList.tsx
  src/pages/admin/ManNewsPost.tsx
  src/pages/admin/ManRecruitDate.tsx
  src/pages/admin/SomkatonApplicants.tsx
  src/setupTests.ts
  src/utils/apiClient.ts
  tsconfig.json
  yarn.lock
Labels: REFACTOR, INFRA

#185 [Refactor] 폴더 추가 & news 페이지 로직 분리
  src/App.tsx
  src/components/UI/MeetingDate.tsx
  src/components/UI/MeetingTimeSelector.tsx
  src/components/UI/NewsNotice.tsx
  src/components/layout/ProtectRoute.tsx
  src/pages/faq/FAQ.tsx
  src/pages/news/News.tsx
  src/pages/news/NewsInfo.tsx
  src/pages/news/NewsService.ts
  src/pages/news/Newstype.ts
  src/pages/recruit/Recruit.tsx
  src/pages/recruit/RecruitCheck.tsx
  src/pages/recruit/RecruitCheckFinal.tsx
  src/pages/recruit/RecruitMeeting.tsx
  src/pages/recruit/RecruitResult.tsx
  src/pages/recruit/RecruitSubmit.tsx
  src/pages/recruit/RecruitSubmitMeeting.tsx
  src/pages/recruit/SomkathonRecruit.tsx
  src/pages/recruit/SomkathonSubmit.tsx
  src/utils/apiClient.ts
  src/utils/imageUtils.ts
Labels: REFACTOR

#191 [Refactor] tsx 로직 분리
  src/pages/Login.tsx
  src/pages/admin/AdminMain.tsx
  src/pages/admin/ManApplicants.tsx
  src/pages/admin/ManInterviewee.tsx
  src/pages/admin/ManNewsDetail.tsx
  src/pages/admin/ManNewsEdit.tsx
  src/pages/admin/ManNewsList.tsx
  src/pages/admin/ManNewsPost.tsx
  src/pages/admin/ManRecruitDate.tsx
  src/pages/admin/SomkatonApplicants.tsx
  src/pages/admin/admin.ts
  src/pages/admin/adminService.ts
  src/pages/recruit/Recruit.tsx
  src/pages/recruit/RecruitCheck.tsx
  src/pages/recruit/RecruitCheckFinal.tsx
  src/pages/recruit/RecruitMeeting.tsx
  src/pages/recruit/RecruitResult.tsx
  src/pages/recruit/RecruitService.ts
  src/pages/recruit/RecruitSubmitMeeting.tsx
  src/pages/recruit/Recruittype.ts
  src/pages/recruit/SomkathonRecruit.tsx
Labels: REFACTOR

#193 [refactor] 페이지 타입분리
  src/App.tsx
  src/components/UI/AdminPagination.tsx
  src/components/UI/FAQ_Section.tsx
  src/components/UI/MeetingDate.tsx
  src/components/UI/MeetingTime.tsx
  src/components/UI/NewsContent.tsx
  src/components/UI/NewsFileUpload.tsx
  src/components/UI/NewsTextEditor.tsx
  src/components/UI/RecruitUI.tsx
  src/components/UI/Recruit_Button.tsx
  src/components/UI/Recruit_InfoBanner.tsx
  src/components/UI/Recruit_InputField.tsx
  src/components/UI/types.ts
  src/pages/admin/index.ts
  src/pages/index.ts
  src/pages/news/index.ts
  src/pages/recruit/RecruitCheckFinal.tsx
  src/pages/recruit/RecruitMeeting.tsx
  src/pages/recruit/RecruitResult.tsx
  src/pages/recruit/RecruitSubmitMeeting.tsx
  src/pages/recruit/index.ts
  src/types/common.ts
  src/types/forms.ts
  src/types/meeting.ts
Labels: REFACTOR

#206 [feat] 헤더 & 푸터 구현
  src/App.tsx
  src/components/UI/Header.tsx
  src/components/layout/Footer.tsx
  src/components/layout/Header.tsx
  src/components/layout/MobileNav.tsx
  src/pages/UserMain.tsx
  src/pages/recruit/RecruitSubmit.tsx
  src/pages/recruit/SomkathonSubmit.tsx
Labels: FEAT

#209 [feat] 메인페이지 구현
  public/coreback.svg
  public/dare.svg
  public/dasomMain.png
  public/share.svg
  public/someday.svg
  src/components/UI/CoreValueCard.tsx
  src/components/UI/ParticlesBackground.tsx
  src/components/UI/Reveal.tsx
  src/components/sections/ActivitiesSection.tsx
  src/components/sections/CoreValuesSection.tsx
  src/components/sections/HeroSection.tsx
  src/components/sections/RecruitingSection.tsx
  src/pages/Main.tsx
Labels: REFACTOR, FEAT

#207 [refactor] 지원 관련 페이지 레이아웃 수정
  src/App.tsx
  src/components/UI/RecruitUI.tsx
  src/components/UI/Recruit_Button.tsx
  src/components/UI/Recruit_InfoBanner.tsx
  src/components/UI/Recruit_InputField.tsx
  src/components/layout/MobileLayout.tsx
  src/pages/recruit/Recruit.tsx
  src/pages/recruit/RecruitCheck.tsx
  src/pages/recruit/RecruitCheckFinal.tsx
  src/pages/recruit/RecruitInfo.tsx
  src/pages/recruit/RecruitMeeting.tsx
  src/pages/recruit/RecruitResult.tsx
  src/pages/recruit/RecruitSubmit.tsx
  src/pages/recruit/RecruitSubmitMeeting.tsx
  src/pages/recruit/Recruittype.ts
  src/pages/recruit/SomkathonRecruit.tsx
  src/pages/recruit/SomkathonSubmit.tsx
  src/pages/recruit/useRecruitForm.ts
  src/pages/recruit/useRecruitSchedule.ts
Labels: REFACTOR

#211 [refactor] 관리자 지원자, 면접자 페이지 UI 수정
  src/App.tsx
  src/components/UI/AdminApplicantButton.tsx
  src/components/UI/AdminPagination.tsx
  src/components/UI/types.ts
  src/pages/admin/ManApplicants.tsx
  src/pages/admin/ManInterviewee.tsx
  src/pages/admin/index.ts
  src/pages/admin/useAdminApplicant.tsx
Labels: REFACTOR

#213 [feat] 조직도 페이지 UI 구현
  package-lock.json
  package.json
  src/App.tsx
  src/assets/images/dasombanner.png
  src/assets/images/github.png
  src/assets/images/source/image 7-1.png
  src/assets/images/source/image 7-2.png
  src/assets/images/source/image 7-3.png
  src/assets/images/source/image 7-4.png
  src/assets/images/source/image 7-5.png
  src/assets/images/source/image 7-6.png
  src/assets/images/source/image 7-7.png
  src/assets/images/source/image 7.png
  src/assets/images/source/image.png
  src/components/common/Banner.tsx
  src/components/layout/Header.tsx
  src/pages/CoreMembers.tsx
  src/pages/news/News.tsx
Labels: REFACTOR, FEAT

#217 [bug] ActivitiesSection 페이지 뉴스 도메인 변경
  src/components/sections/ActivitiesSection.tsx
Labels: BUG

#222 [hotfix] api 요청 url 수정 및 news 이미지 convert함수 수정
  src/App.tsx
  src/pages/Login.tsx
  src/pages/admin/ManNewsDetail.tsx
  src/pages/admin/adminService.ts
  src/utils/imageUtils.ts
Labels: BUG, HOTFIX

#221 [hotfix] 캘린더 UI 문제 수정
  src/components/UI/RecruitCalendar.tsx
Labels: HOTFIX

#223 [hotfix] 조직도 api 연동
  src/pages/CoreMembers.tsx
Labels: HOTFIX

#225 [feat] 버튼 동적 구현
  src/components/UI/RecruitCalendar.tsx
  src/components/UI/RecruitInfo_Button.tsx
  src/pages/recruit/RecruitInfo.tsx
Labels: FEAT
